error.general: 'There was an unexpected error. Please try again later.'
success.user_deleted: 'The user "{{ username }}" was successfully deleted'
